## Random Graphs

### Helper Functions

Randomly generate an adjancency matrix...

In [4]:
import timeit
import random
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from itertools import combinations, groupby

# Size of NxN Matrix
n = 4

# Moved to global scopee to allow for timing
bf_bit_string, bf_cost = None, None

def random_row(row_num: int):
    row = list(np.random.choice((0, 1, 2, 3, 4, 5),size=n))
    
    row[row_num] = 0 
    
    # Make sure there's no isolated nodes
    if sum(row) == 0:
        row = random_row(row_num)
    return row

def random_matrix():
    rows = []
    for i in range(0, n):
        rows.append(random_row(i))
    numpy_matrix = np.matrix(rows)
    
    return numpy_matrix

def random_graph():
    np_matrix = random_matrix()
    g = nx.convert_matrix.from_numpy_matrix(
        np_matrix, 
        parallel_edges=False, 
        create_using=nx.Graph
    )
    
    # nx.draw(g, node_color='lightblue', 
    #     with_labels=True, 
    #     node_size=500)
    
    return g, np_matrix

### Brute Force

In [2]:
def brute_force(graph, w):
    global bf_bit_string
    global bf_cost
    
    bf_bit_string = None
    bf_cost = None
    
    best_cost_brute = 0
    for b in range(2**n):
        x = [int(t) for t in reversed(list(bin(b)[2:].zfill(n)))]
        cost = 0
        for i in range(n):
            for j in range(n):
                cost = cost + w[i,j]*x[i]*(1-x[j])
        if best_cost_brute < cost:
            best_cost_brute = cost
            xbest_brute = x
    bf_bit_string = xbest_brute
    bf_cost = best_cost_brute
    return xbest_brute, best_cost_brute

### Quantum Apporximation Optimization Algorithm

In [3]:
import networkx as nx
import numpy as np
import plotly.graph_objects as go
import matplotlib as mpl
import pandas as pd
from IPython.display import clear_output
from plotly.subplots import make_subplots
from matplotlib import pyplot as plt
from qiskit import Aer
from qiskit import QuantumCircuit
from qiskit.visualization import plot_state_city
from qiskit.algorithms.optimizers import COBYLA, SLSQP, ADAM
from time import time
from copy import copy
from typing import List
from qc_grader.graph_util import display_maxcut_widget, QAOA_widget, graphs
from qiskit.circuit import Parameter, ParameterVector
from qiskit_optimization import QuadraticProgram
from qiskit.algorithms import QAOA
from qiskit_optimization.algorithms import MinimumEigenOptimizer

def maxcut_cost_fn(graph: nx.Graph, bitstring: List[int]) -> float:
    """
    Computes the maxcut cost function value for a given graph and cut represented by some bitstring
    Args:
        graph: The graph to compute cut values for
        bitstring: A list of integer values '0' or '1' specifying a cut of the graph
    Returns:
        The value of the cut
    """
    #Get the weight matrix of the graph
    weight_matrix = nx.adjacency_matrix(graph).toarray()
    size = weight_matrix.shape[0]
    value = 0.
    for i in range(size):
        for j in range(size):
            value = value + weight_matrix[i][j] * bitstring[i] * (1-bitstring[j])

    return value

def quadratic_program_from_graph(graph: nx.Graph) -> QuadraticProgram:
    """Constructs a quadratic program from a given graph for a MaxCut problem instance.
    Args:
        graph: Underlying graph of the problem.
    Returns:
        QuadraticProgram
    """
    #Get weight matrix of graph
    weight_matrix = nx.adjacency_matrix(graph)
    shape = weight_matrix.shape
    size = shape[0]
    
    #Build qubo matrix Q from weight matrix W
    qubo_matrix = np.zeros((size, size))
    qubo_vector = np.zeros(size)
    for i in range(size):
        for j in range(size):
            qubo_matrix[i, j] -= weight_matrix[i, j]
    for i in range(size):
        for j in range(size):
            qubo_vector[i] += weight_matrix[i,j]

    quadratic_program = QuadraticProgram('MaxCut as QUBO')
    for i in range(size):
        quadratic_program.binary_var(name = f'x_{i}')

    quadratic_program.maximize(quadratic = qubo_matrix, linear = qubo_vector)
    
    return quadratic_program

def qaoa_circuit(qubo: QuadraticProgram, p: int = 1, params: dict = []) -> QuantumCircuit:
    """
    Given a QUBO instance and the number of layers p, constructs the corresponding parameterized QAOA circuit with p layers.
    Args:
        qubo: The quadratic program instance
        p: The number of layers in the QAOA circuit
    Returns:
        The parameterized QAOA circuit
    """
    size = len(qubo.variables)
    qubo_matrix = qubo.objective.quadratic.to_array(symmetric=True)
    qubo_linearity = qubo.objective.linear.to_array()

    #Prepare the quantum and classical registers
    qaoa_circuit = QuantumCircuit(size,size)
    #Apply the initial layer of Hadamard gates to all qubits
    qaoa_circuit.h(range(size))

    #Create the parameters to be used in the circuit
    if not params:
        gammas = ParameterVector('gamma', p)
        betas = ParameterVector('beta', p)
    else:
        gammas = [params[1]]
        betas = [params[0]]

    #Outer loop to create each layer
    for i in range(p):

        #Apply R_Z rotational gates from cost layer
        for qubit in range(size):
            sum =0
            for col in range(size):
                sum += qubo_matrix[qubit][col]
            theta = (qubo_linearity[qubit] + sum) * gammas[i]
            qaoa_circuit.rz(theta, qubit)

        #Apply R_ZZ rotational gates for entangled qubit rotations from cost layer
        for j in range(size):
            for k in range(size):
                if j != k:
                    theta = qubo_matrix[j][k] * gammas[i] / 2
                    qaoa_circuit.rzz(theta, j, k)

        # Apply single qubit X - rotations with angle 2*beta_i to all qubits
        for qubit in range(size):
            qaoa_circuit.rx(2 * betas[i], qubit)
    return qaoa_circuit

def plot_qaoa_energy_landscape(graph: nx.Graph, cvar: float = None, plot: bool = True):
    num_shots = 1000
    seed = 42
    simulator = Aer.get_backend('qasm_simulator')
    simulator.set_options(seed_simulator = 42)

    #Generate circuit
    circuit = qaoa_circuit(qubo = quadratic_program_from_graph(graph), p=1)
    circuit.measure(range(graph.number_of_nodes()),range(graph.number_of_nodes()))

    #Create dictionary with precomputed cut values for all bitstrings 
    cut_values = {}
    size = graph.number_of_nodes()
    for i in range(2**size):
        bitstr = '{:b}'.format(i).rjust(size, '0')[::-1]
        x = [int(bit) for bit in bitstr]
        cut_values[bitstr] = maxcut_cost_fn(graph, x)

    #Perform grid search over all parameters
    data_points = []
    max_energy = None
    for beta in np.linspace(0,np.pi, 50):
        for gamma in np.linspace(0, 4*np.pi, 50):
            bound_circuit = circuit.assign_parameters([beta, gamma])
            result = simulator.run(bound_circuit, shots = num_shots).result()
            statevector = result.get_counts(bound_circuit)
            energy = 0
            measured_cuts = []
            for bitstring, count in statevector.items():
                measured_cuts =  measured_cuts + [cut_values[bitstring]]*count

            if cvar is None:
                # Calculate the mean of all cut values
                energy = sum(measured_cuts)/num_shots
            else:
                alpha_n = cvar*num_shots
                measured_cuts.sort(reverse=True)
                energy = sum(measured_cuts[:int(alpha_n)])/alpha_n

            #Update optimal parameters
            if max_energy is None or energy > max_energy:
                max_energy = energy
                optimum = {'beta': beta, 'gamma': gamma, 'energy': energy}

            #Update data
            data_points.append({'beta': beta, 'gamma': gamma, 'energy': energy})

    if plot:
        #Create and display surface plot from data_points
        df = pd.DataFrame(data_points)
        df = df.pivot(index='beta', columns='gamma', values='energy')
        matrix = df.to_numpy()
        beta_values = df.index.tolist()
        gamma_values = df.columns.tolist()

        surface_plot = go.Surface(
            x=gamma_values, 
            y=beta_values,
            z=matrix,
            coloraxis = 'coloraxis'
        )
        fig = go.Figure(data = surface_plot)
        fig.show()

    #Return optimum
    return optimum

def qaoa(nx_g):
    """
    Outline of how to use the QAOA class
        problem = QuadraticProgram()
        # specify problem here
        # specify minimum eigen solver to be used, e.g., QAOA
        qaoa = QAOA(...)
        optimizer = MinimumEigenOptimizer(qaoa)
        result = optimizer.solve(problem)
    
    """
    backend = Aer.get_backend('statevector_simulator')
    qaoa = QAOA(optimizer = ADAM(), quantum_instance = backend, reps=1, initial_point = [0.1,0.1])
    eigen_optimizer = MinimumEigenOptimizer(min_eigen_solver = qaoa)
    quadratic_program = quadratic_program_from_graph(nx_g)
    result = eigen_optimizer.solve(quadratic_program)
    
    # print results
    bit_string = map(int, result.x)
    return bit_string, result.fval, result.min_eigen_solver_result.optimizer_time
    

Traceback (most recent call last):
  Input In [6] in <cell line: 16>
    from qc_grader.graph_util import display_maxcut_widget, QAOA_widget, graphs
ModuleNotFoundError: No module named 'qc_grader.graph_util'

Use %tb to get the full traceback.


## Tests

In [ ]:
# Generate 1,000 graphs
success = 0
failure = 0

# TODO: Change the number of tests, ad hoc
num_tests: int = 100

for graph_id in range(num_tests):
    global bf_bit_string
    global bf_cost
    
    # Generate Random Graph
    graph, matrix = random_graph()
    
    # Computing the weight matrix from the random graph
    w = np.zeros([n,n])
    for i in range(n):
        for j in range(n):
            temp = graph.get_edge_data(i,j,default=0)
            if temp != 0:
                w[i,j] = temp['weight']
    
    print(f'\nTest Case {graph_id}: ')
    print('------------' + '-' * (len(str(graph_id)) * 2))
    print()
    print(w)
    
    # Brute Force Approach
    #
    # Time brute force algorithm
    bf_time: float = timeit.timeit(lambda: brute_force(graph, w), number=1)
    
    # Parse the bit sting answer
    bf_x = ''.join(str(e) for e in bf_bit_string)
    bf_x_inverse = ''.join('1' if x == '0' else '0' for x in bf_x)
    
    # Print results
    print('\n\tBrute Force')
    print(f'\t\tSolution = {bf_x} [{bf_x_inverse}].')
    print(f'\t\tMaxcut = {str(bf_cost)}.')
    print(f'\t\tTime: {bf_time} seconds.')
    
    # QAOA Approach
    #
    # Run QAOA
    qaoa_bit_string, qaoa_cost, qaoa_optimizer_time = qaoa(graph)
    
    # Parse the bit sting answer
    qaoa_x = ''.join(str(e) for e in qaoa_bit_string)
    qaoa_x_inverse = ''.join('1' if x == '0' else '0' for x in qaoa_x)
    
    # Print results
    print('\n\tQuantum Approximation Optimization Algorithm (QAOA):')
    print(f'\t\tSolution = {qaoa_x} [{qaoa_x_inverse}].')
    print(f'\t\tMaxcut = {str(qaoa_cost)}.')
    print(f'\t\tOptimizer Time: {str(qaoa_optimizer_time)} seconds.')
    # print(f'\t\tCompmute Minimum Eigenvalue Time: {str(optimizer_time)} seconds.')
    print()
    
    # Check validity
    if bf_x == qaoa_x or bf_x == qaoa_x_inverse or qaoa_x == bf_x_inverse:
        success += 1
    else:
        failure += 1


Test Case 0: 
--------------

[[0. 5. 4. 2.]
 [5. 0. 4. 1.]
 [4. 4. 0. 1.]
 [2. 1. 1. 0.]]

	Brute Force
		Solution = 1010 [0101].
		Maxcut = 12.0.
		Time: 0.004632885043974966 seconds.
Traceback (most recent call last):
  Input In [7] in <cell line: 8>
    qaoa_bit_string, qaoa_cost, qaoa_optimizer_time = qaoa(graph)
NameError: name 'qaoa' is not defined

Use %tb to get the full traceback.


In [ ]:
print(f'Success: {success} / {num_tests} = {(success/num_tests) * 100} %')
print(f'Fail: {failure} / {num_tests} = {(failure/num_tests) * 100} %')

Success: 0 / 100 = 0.0 %
Fail: 0 / 100 = 0.0 %
